# Generated by Django 5.0 on 2025-10-16 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkoutfeedback'),
        ('movies', '0004_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.region'),
        ),
    ]
