# Generated by Django 5.0 on 2025-10-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
    ]
