# Generated by Django 5.0 on 2025-10-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
