# Generated by Django 5.0 on 2025-10-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_order_city'),
        ('movies', '0007_region_remove_userprofile_city_userprofile_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.region'),
        ),
    ]
